[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[phases.setup]
aptPkgs = ["chromium-browser", "chromium-chromedriver"] 